# Generated by Django 5.1.5 on 2025-02-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_beforeafter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeforeAfter',
            new_name='BeforeAfterSwiper',
        ),
    ]
