# Generated by Django 4.2.15 on 2025-02-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_testimonial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeafterswiper',
            name='after_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='beforeafterswiper',
            name='before_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
