# Generated by Django 4.2.15 on 2025-02-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_beforeafterswiper_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeafterswiper',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='beforeafterswiper',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
