# Generated by Django 4.2.15 on 2025-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_beforeafterswiper_after_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
